### ISSUE TITLE
YAML multi-line strings inconsistencies

### ISSUE THREAD

**Issue by ItalyPaleAle** [alecthomas/chroma#475] opened 2021-04-25 21:23 UTC
In recent updates to Chroma, yaml multi-line strings (starting with `|`) seem to be rendered inconsistently.

Example:

```yaml
steps:

  # Sets FOO to be "some value" in the script and the next ones
  - bash: |
      FOO="some value"
      echo "##vso[task.setvariable variable=FOO]$FOO"

  # Using the $() syntax, the value is replaced inside Azure Pipelines before being submitted to the script task
  - bash: |
      echo "$(FOO)"

  # The same variable is also present as environmental variable in scripts; here the variable expansion happens within bash
  - bash: |
      echo "$FOO"
```

This renders as:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/43508/116010054-af233480-a5d1-11eb-86a4-804b29cda378.png">

As you can see, if there's a single line in the multiline string, the number of spaces at the beginning is increased (to match the | character's position). The color is also different.
Adding more than one line with the same indentation (even if empty), fixes that.

While the resulting, rendered YAML is valid, it looks odd

**Comment by silverwind** [comment] 2021-08-10 12:28
It seems that whitespace is rendered twice. Simple repro:

````
key: |
  value
````

HTML of second line:
````html
<span style="color:#d88200">  </span>  <span style="color:#ae81ff">value</span>
````

The 2 spaces are rendered highlighted once inside the first `<span>` and then again unhighlighted following that span.

**Comment by alecthomas** [comment] 2021-09-18 08:46
Unfortunately YAML is horrifically difficult to parse, and Chroma's lexer is consequently not that robust. You can see the complexity in the [Pygments lexer](https://github.com/pygments/pygments/blob/1df7fd71dad01c939da89d70947d2d606d7c21fa/pygments/lexers/data.py#L19-L433).

**Comment by jmooring** [comment] 2023-02-28 23:29
I think this was resolved with https://github.com/alecthomas/chroma/pull/724. I am now unable to reproduce the problem.

**Closed** 2023-03-01 03:29 UTC
Labels: help wanted, lexer bug
