### ISSUE TITLE
Highlighting issues with `greater than` character in hugo

### ISSUE THREAD

**Issue by zbayoff** [alecthomas/chroma#262] opened 2019-07-19 15:55 UTC
I am using Chroma which is built into hugo static site generator v0.55.3 
When using code fences for yaml like so:
```
```yaml
      logs:
        - type: file
          path: <TAG>/text/text.log
          service: <SERVICE_NAME>  
          source: file
        - type: file
          path: <TAG>/text/text.log
          service:  <SERVICE_NAME>  
          source: file
    ```
```

I get the following output: 
![image](https://user-images.githubusercontent.com/30878344/61548517-dff93180-aa1b-11e9-89a7-c0d515fde6ba.png)

with the greater than symbols at the end highlighted oddly. Is there an escape I need to use for these characters? 

I tried using double quotes around the text with the gt characters and got: 
![image](https://user-images.githubusercontent.com/30878344/61548592-06b76800-aa1c-11e9-85ba-c5bc7fe2062b.png)
 but would rather not have the double quotes rendered.

**Comment by alecthomas** [comment] 2019-09-22 23:14
The YAML lexer is rudimentary, as YAML itself is insanely complicated and writing a fully compliant YAML lexer is painful. TBH I have no time to fix it. Contributions welcome.

**Comment by alecthomas** [comment] 2019-09-22 23:14
This is a duplicate of #118.

**Closed by alecthomas** 2019-09-22 23:14 UTC
Labels: bug, help wanted
