### ISSUE TITLE
Makefile regexp crash

### ISSUE THREAD

**Issue by rcoreilly** [alecthomas/chroma#424] opened 2020-11-16 11:27 UTC
**Describe the bug**

Crashed with a bad regexp when parsing a Makefile.  This must be relatively recent as I just updated everything and this 
occurred -- wasn't a problem before.  It seems like a straightforward issue with a bad regexp that shouldn't depend on anything specific in my use-case -- let me know if further details might be relevant and I can provide them.

```
panic: failed to compile rule basic.8: error parsing regexp: malformed \k<...> named back reference in `\G(?m)(?:<<-?\s*(\'?)\\?(\w+)[\w\W]+?\2)`

goroutine 11 [running]:
github.com/alecthomas/chroma.Using.func1(0xc0160410c0, 0x1, 0x1, 0x5196b20, 0xc00039f590, 0x1)
        /Users/oreilly/go/src/github.com/alecthomas/chroma/regexp.go:123 +0xd4
github.com/alecthomas/chroma.EmitterFunc.Emit(0xc0003ee5e0, 0xc0160410c0, 0x1, 0x1, 0x5196b20, 0xc00039f590, 0x10)
        /Users/oreilly/go/src/github.com/alecthomas/chroma/regexp.go:32 +0x58
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc000713040, 0x2, 0xc0092be000, 0x389)
        /Users/oreilly/go/src/github.com/alecthomas/chroma/regexp.go:326 +0x622
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1(0x4011038, 0x20, 0x4e2f660)
        /Users/oreilly/go/src/github.com/alecthomas/chroma/coalesce.go:15 +0x5a
github.com/alecthomas/chroma.Iterator.Tokens(0xc000a94060, 0x0, 0xc008d64c00, 0xbb4)
        /Users/oreilly/go/src/github.com/alecthomas/chroma/iterator.go:15 +0x3c
```

**Comment by alecthomas** [comment] 2020-11-16 11:49
I can't replicate this on the Makefiles I've tried it on, so I'll need a minimal input that reproduces the panic if you can.

**Comment by rcoreilly** [comment] 2020-11-16 12:07
It appears to be this "basic"[8] case in `lexers/b/bash.go`

```
			{`<<-?\s*(\'?)\\?(\w+)[\w\W]+?\2`, LiteralString, nil},
```

I tried reverting to v0.7.3 which should have been what I was on before, but it is still crashing, making me think that there is some other thing that was updated that is indirectly causing this problem.  I'll do some more investigation and report back.

**Comment by rcoreilly** [comment] 2020-11-16 12:16
well, that's interesting!  I'm using GOPATH in this case, not go modules, and I just ran an ill-advised `go get -u ./...`  in this case, if you grab the latest chroma, build cmd/chroma, and run it on your own Makefile, it gives the same crash!

```
oreilly@shadow:~/go/src/github.com/alecthomas/chroma/ > chroma Makefile 
.PHONY: chromad upload allpanic: failed to compile rule basic.8: error parsing regexp: malformed \k<...> named back reference in `\G(?m)(?:<<-?\s*(\'?)\\?(\w+)[\w\W]+?\2)`

goroutine 1 [running]:
github.com/alecthomas/chroma.Using.func1(0xc0002e92c0, 0x1, 0x1, 0x14c1d80, 0xc0002de660, 0x1)
	/Users/oreilly/go/src/github.com/alecthomas/chroma/regexp.go:123 +0xd4
github.com/alecthomas/chroma.EmitterFunc.Emit(0xc0002c7d80, 0xc0002e92c0, 0x1, 0x1, 0x14c1d80, 0xc0002de660, 0x10)
	/Users/oreilly/go/src/github.com/alecthomas/chroma/regexp.go:32 +0x58
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc0000cc780, 0xc0003a3c68, 0x10defd1, 0x16a5ba0)
	/Users/oreilly/go/src/github.com/alecthomas/chroma/regexp.go:326 +0x622
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1(0x92d0238, 0xc00042bb80, 0xc0003a3d60)
	/Users/oreilly/go/src/github.com/alecthomas/chroma/coalesce.go:15 +0x38
github.com/alecthomas/chroma/formatters.(*indexedTTYFormatter).Format(0xc0000b0028, 0x92d0238, 0xc00042bb80, 0xc000345460, 0xc000345f20, 0xc0002de601, 0x92d0238)
	/Users/oreilly/go/src/github.com/alecthomas/chroma/formatters/tty_indexed.go:229 +0x89
main.format(0xc0003def80, 0x92d0238, 0xc00042bb80, 0xc000345460, 0xc000345f20)
	/Users/oreilly/go/src/github.com/alecthomas/chroma/cmd/chroma/main.go:267 +0x9a
main.main()
	/Users/oreilly/go/src/github.com/alecthomas/chroma/cmd/chroma/main.go:167 +0x951
```

from looking at go.mod, most likely it is some change in dlclark/regexp2 ?  I'll try reverting to 1.2.0

**Comment by rcoreilly** [comment] 2020-11-16 12:23
Yeah you can see the latest commits there look suspicious with respect to this `\k` thing.  Reverting to the last tagged release, v.1.4.0, works fine!  You might want to take up this issue with dlclark..

**Comment by rcoreilly** [comment] 2020-11-16 12:33
https://github.com/dlclark/regexp2/commit/9ff549bdea771caf9ee378ad8ba85cafc40facbb

commit message:
```
Improved the handling of named group references in ECMAScript mode:
- \k<name> is only parsed as a named group reference if there is at least one group name (?<anyname>) in the regexp.
- No support for \<name>, \k'name' or \'name' notations.
- Fail on invalid group name references (empty or containing non-word characters). This affects all modes, not just ECMAScript.
```

**Comment by alecthomas** [comment] 2020-11-16 12:45
@dlclark FYI

**Comment by alecthomas** [comment] 2020-11-16 12:45
Thanks for investigating!

**Comment by dop251** [comment] 2020-11-16 13:16
Looks like I broke it, my bad. This should fix it: https://github.com/dlclark/regexp2/pull/40

**Comment by dlclark** [comment] 2020-11-16 16:44
Sorry folks, definitely a bug on our end.  Should now be resolved in master: https://github.com/dlclark/regexp2/commit/a2a8dda75c91d84f7daa4154f32385f65b101bf2

**Comment by alecthomas** [comment] 2020-11-16 20:27
Thanks Doug!

**Closed** 2021-02-05 23:13 UTC
