### ISSUE TITLE
jsx render error

### ISSUE THREAD

**Issue by Vanessa219** [alecthomas/chroma#291] opened 2019-10-11 00:56 UTC
Github is ok， but a rendering error occurs in  https://hacpai.com/article/1570754498261#toc_h3_2. 

`/React.Fragment>` has class `highlight-err`

code:
```jsx
//Add the component to the render function
function App() {
  const [isModal, setModal] = React.useState(false);

  return (
    <React.Fragment>
      <button onClick={() => setModal(true)}>Click Here</button>
      <Modal
        isVisible={isModal}
        title="Modal Title"
        content={<p>Add your content here</p>}
        footer={<button>Cancel</button>}
        onClose={() => setModal(false)}
      />
    </React.Fragment>
  );
}

ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by dguo** [comment] 2019-12-10 03:23
The same thing seems to happen (I'm indirectly using Chroma through Hugo) with the shorthand syntax for Fragments:

```jsx
function App() {
    return (
        <>
            <p>test</p>
        </>
    );
}
```

I get error highlighting for the `/>` part of the closing Fragment tag.

**Comment by phelipetls** [comment] 2022-08-24 13:19
It looks like this issue has been resolved? I couldn't reproduce them.

Fragment is highlighted normally in the OP's website:
![image](https://user-images.githubusercontent.com/39670535/186428434-72bdc0b5-e85b-4d0b-a4fd-a366206ed806.png)

The second reported issue doesn't seem to occur using Hugo v101 (not sure which chroma version is being used)
![image](https://user-images.githubusercontent.com/39670535/186428370-1224ecd3-9a39-4fad-a8d2-16161603e576.png)

**Closed** 2022-08-24 14:17 UTC
Labels: help wanted, lexer bug
