### ISSUE TITLE
Hex number is incorrectly highlighted

### ISSUE THREAD

**Issue by duongdominhchau** [alecthomas/chroma#374] opened 2020-06-23 13:24 UTC
![image](https://user-images.githubusercontent.com/56427890/85408784-2e4d7380-b58f-11ea-8dad-a8004a675683.png)

`0xff` is misrecognized so only `0` is highlighted. This bug occurs on both Hugo and the Chroma Playground.

**Comment by serhack** [comment] 2022-11-11 11:34
I can't reproduce it, could we close it? @alecthomas 

![image](https://user-images.githubusercontent.com/27734319/201332193-6bd05018-afe4-4cc0-a4df-fa20e2dcd4da.png)

**Comment by alecthomas** [comment] 2022-11-13 08:11
Nice, thanks for checking

**Closed** 2022-11-13 08:11 UTC
Labels: help wanted, lexer enhancement
